Repository hmcts/cmc-claim-store, pull requests merged in 2018-03, with the labels that each got.

#248 ROC-3252 Add fallback for bulk print
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/MockSpringTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/BulkPrintIssueTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/BulkPrintRequestTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/ResendStaffNotificationsTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/BulkPrintStaffNotificationServiceTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/emails/StaffEmailTemplates.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/bulkprint/BulkPrintEmailContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/bulkprint/BulkPrintPDFContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/DocumentReadyToPrintEvent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentGenerator.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/BulkPrintStaffNotificationService.java
  src/main/resources/staff/templates/email/bulkPrintFailure/body.txt
  src/main/resources/staff/templates/email/bulkPrintFailure/subject.txt
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/DocumentGeneratorTest.java
Labels: pull-request: approved, tested

#253 ROC-2892: Sync settlement agreement PDF with prototype
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/PartyDetailsContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/models/PartyDetailsContent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/settlementagreement/SettlementAgreementPDFContentProvider.java
  src/main/resources/staff/templates/document/settlementAgreement.html
Labels: tested

#263 Remove 404 from root
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/RootTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/RootController.java
Labels: pull-request: approved, tested

#255 ROC-2906: Send agreement counter signed notifications to citizens
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/BaseOfferTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/AcceptOrRejectOfferTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/services/citizen/SettlementReachedCitizenNotificationTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/notifications/EmailTemplates.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/AgreementCounterSignedCitizenActionsHandler.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/OfferMadeCitizenActionsHandler.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/offer/OfferRespondedCitizenActionsHandler.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationReferenceBuilder.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/content/NotificationTemplateParameters.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/OfferMadeCitizenActionsHandlerTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/events/offer/OfferRespondedCitizenActionsHandlerTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/NotificationServiceTest.java
Labels: pull-request: approved, tested

#260 ROC-3303 Claim form pdf content revision
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/utils/PartyUtils.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/utils/PartyUtilsTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/DownloadRepresentedClaimCopyWithDocumentManagementTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveClaimWithDocumentManagementTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ClaimantContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/PersonContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/ClaimantContent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/PersonContent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/utils/DocumentNameUtils.java
  src/main/resources/citizen/templates/document/claimIssueReceipt.html
  src/main/resources/staff/templates/document/sealedClaim.html
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/ClaimantContentProviderTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/PersonContentProviderTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/utils/DocumentNameUtilsTest.java
Labels: pull-request: approved

#279 ROC-3304: Defence PDF content revision
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/FullDefenceResponse.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/utils/PartyUtils.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/utils/PartyUtilsTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/pdf/DocumentTemplates.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/DocumentsController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseCopyService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantResponseContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/PartyDetailsContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/models/PartyDetailsContent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/AlwaysGenerateDocumentsService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentManagementBackedDocumentsService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/DocumentsService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/DefendantResponseStaffNotificationService.java
  src/main/resources/citizen/templates/document/defendantResponseReceipt.html
  src/main/resources/staff/templates/document/defendantResponseCopy.html
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/DefendantResponseCopyServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/PartyDetailsContentProviderTest.java
Labels: pull-request: approved, tested

#284 ROC-3417: make timeline optional for defendant
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/DefendantTimeline.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/DefendantTimelineTest.java
  src/main/resources/citizen/templates/document/defendantResponseReceipt.html
Labels: pull-request: approved

#285 ROC-3370: Make first contact URL configurable
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  src/integrationTest/resources/environment.properties
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/properties/notifications/NotificationsProperties.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/ClaimIssuedNotificationService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/notifications/content/NotificationTemplateParameters.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/DefendantPinLetterContentProvider.java
  src/main/resources/application.yml
  src/main/resources/staff/templates/document/defendantPinLetter.html
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/BaseNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/notifications/ClaimIssuedNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/DefendantPinLetterContentProviderTest.java
Labels: pull-request: approved, tested

#276 ROC-3370: Point service to new GOV.UK pages
  infrastructure/prod.tfvars
Labels: pull-request: approved

#296 ROC-3455: Fix for defendant journey broken for interest
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Claim.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculatorTest.java
Labels: pull-request: approved, tested
