Repository hmcts/cmc-claim-store, pull requests merged in 2018-04, with the labels that each got.

#282 ROC-3377: Update CCJ PDF
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationServiceTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/CCJStaffNotificationService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/AmountContent.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/AmountContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/ContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/models/CCJContent.java
  src/main/resources/staff/templates/document/countyCourtJudgmentDetails.html
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/countycourtjudgment/ContentProviderTest.java
Labels: pull-request: approved, tested locally

#301 ROC-3407: Make defence text optional
  ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/mapper/response/ResponseMapper.java
  ccd-adapter/src/test/java/uk/gov/hmcts/cmc/ccd/assertion/ResponseAssert.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/FullDefenceResponse.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/ResponseTest.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/SaveDefendantResponseTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantResponseContentProvider.java
  src/main/resources/citizen/templates/document/defendantResponseReceipt.html
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/content/DefendantResponseContentProviderTest.java
Labels: pull-request: approved

#303 ROC-3481: fix bug
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/amount/TotalAmountCalculator.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/InterestDate.java
  domain-model/src/test/java/uk/gov/hmcts/cmc/domain/models/InterestDateTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/ClaimDataContentProvider.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProvider.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/staff/content/InterestContentProviderTest.java
Labels: pull-request: approved, tested locally

#321 FIX: throw exception when claim is not linked with defendant
  src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/RespondToClaimTest.java
  src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/functional/SettlementOfferTest.java
  src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/helpers/CommonOperations.java
  src/aat/java/uk/gov/hmcts/cmc/claimstore/tests/idam/IdamTestService.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/ClaimStore.java
  src/integrationTest/java/uk/gov/hmcts/cmc/claimstore/controllers/errors/EndpointErrorsTest.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CCDCaseRepository.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/CaseRepository.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/ClaimRepository.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/repositories/DBCaseRepository.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/ClaimService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/DefendantResponseService.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/DefendantResponseServiceTest.java
Labels: tested locally
