Repository hmcts/cmc-claim-store, pull requests merged in 2022-09, with the labels that each got.

#2628 claimant respond to order email template change
  src/main/resources/application.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2628

#2629 fix master - supress CVE-2022-25857
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2629

#2630 Fix CVE-2022-25857
  build.gradle
  config/owasp/suppressions.xml
  launch-darkly-client/build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2630

#2634 CIV-4743: Fix deprecation warnings
  build.gradle
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/BreathingSpace.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/Payment.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/JacksonConfiguration.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2634
