Repository hmcts/cmc-claim-store, pull requests merged in 2022-03, with the labels that each got.

#2555 Enable security scan in Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2555

#2556 CIV-1494 : upgraded base helm charts
  charts/cmc-claim-store/Chart.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2556

#2553 CIV-1188 : implemented new git workflow codeql analysis for security …
  .github/workflows/codeql-analysis.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2553

#2566 CIV-1653 : suppressed dependency vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2566
