Repository hmcts/cmc-claim-store, pull requests merged in 2022-02, with the labels that each got.

#2533 CIV-512: Added new CCD hearing duration type
  ccd-adapter/src/main/java/uk/gov/hmcts/cmc/ccd/domain/legaladvisor/CCDHearingDurationType.java
  domain-model/src/main/java/uk/gov/hmcts/cmc/domain/models/orders/HearingDurationType.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/legaladvisor/DrawJudgeOrderCallbackHandlerTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2533

#2537 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2537

#2539 CIV-1167 : updated state.tf to include azurerm send grid subscription
  infrastructure/state.tf
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2539

#2540 Clear helm release on successful build
  Jenkinsfile_CNP
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2540

#2542 CIV-1262 : temp suppressed owasp warnings
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2542

#2545 CIV-1186 : added default reviewers
  .github/CODEOWNERS
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2545

#2549 CIV-1337 : temporarily suppress security vulnerability
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2549

#2547 CIV-1253 : updated deprecated chart configuration
  charts/cmc-claim-store/Chart.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2547

#2554 CIV-1378 : resolved cross-site scripting vulnerability with deadline …
  config/checkstyle/checkstyle.xml
  src/main/java/uk/gov/hmcts/cmc/claimstore/constants/ResponseConstants.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportController.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportControllerTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2554
