Repository hmcts/cmc-claim-store, pull requests merged in 2023-03, with the labels that each got.

#2715 add suppression
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2715

#2716 update azurerm and tf
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:money-claims, prd:cmc, add-or-update, rel:cmc-claim-store-pr-2716

#2713 CIV-7424 Upgrade Send letter client
  build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2713

#2719 CIV-7069: Migrate from swagger to OpenAPI
  build.gradle
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/OpenApiConfiguration.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CalendarController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CallbackController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ClaimantResponseController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CountyCourtJudgmentController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/CourtFinderController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/DefendantResponseController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/DocumentsController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/IntegrationTestSupportController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/InterestRatesController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/OffersController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ResponseDeadlineController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/ScannedDocumentsController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/SettlementAgreementController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/UserRolesController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/CaseMetadataController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/DeadlineSupportController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/RoboticsSupportController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/SupportController.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/support/orders/BulkPrintSupportController.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2719

#2721 CIV-7070 Upgrade springboot version
  build.gradle
  charts/cmc-claim-store/Chart.yaml
  config/owasp/suppressions.xml
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2721

#2717 CIV-7396
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataService.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceFailureTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/CoreCaseDataServiceTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2717

#2723 Fixed CVEs
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2723
