Repository hmcts/cmc-claim-store, pull requests merged in 2023-04, with the labels that each got.

#2728 Fix pipelines
  Dockerfile
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2728

#2726 Update Dockerfile
  Dockerfile
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2726

#2702 CIV-490 fees keywords changes with feature flag
  build.gradle
  charts/cmc-claim-store/Chart.yaml
  charts/cmc-claim-store/values.yaml
  src/main/java/uk/gov/hmcts/reform/fees/client/FeesApi.java
  src/main/java/uk/gov/hmcts/reform/fees/client/FeesClient.java
  src/main/java/uk/gov/hmcts/reform/fees/client/config/FeesClientAutoConfiguration.java
  src/main/java/uk/gov/hmcts/reform/fees/client/health/FeesHealthIndicator.java
  src/main/java/uk/gov/hmcts/reform/fees/client/health/InternalHealth.java
  src/main/java/uk/gov/hmcts/reform/fees/client/model/FeeLookupResponseDto.java
  src/main/resources/application.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2702

#2731 CIV-4887: Fix for CVE-2022-31197
  build.gradle
  config/owasp/suppressions.xml
  job-scheduler/build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2731

#2732 CIV-6101: Fix CVE-2022-41854
  build.gradle
  config/owasp/suppressions.xml
  launch-darkly-client/build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2732

#2734 CIV-8036
  README.md
  charts/cmc-claim-store/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2734
