Repository hmcts/cmc-claim-store, pull requests merged in 2023-05, with the labels that each got.

#2741 add suppressions
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2741

#2738 CIV-8367: Fix CVE-2023-20860
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2738

#2735 CIV-7830: Fix WebSecurityConfigurerAdapter Deprecated
  src/main/java/uk/gov/hmcts/cmc/claimstore/config/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverter.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/security/JwtGrantedAuthoritiesConverterTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2735

#2743 CIV-5002 resolve Feign exception
  README.md
  src/main/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandler.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/controllers/advices/ResourceExceptionHandlerTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2743

#2745 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2745

#2746 CIV-490 Enable Fee and Pay Keywords
  charts/cmc-claim-store/Chart.yaml
  charts/cmc-claim-store/values.yaml
  src/main/resources/application.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2746

#2747 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2747
