Repository hmcts/cmc-claim-store, pull requests merged in 2023-11, with the labels that each got.

#2796 CIV-0000 Add suppression
  charts/cmc-claim-store/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2796

#2798 CIV-10543 changes for master
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:money-claims, prd:cmc, add-or-update, rel:cmc-claim-store-pr-2798

#2799 Revert "CIV-10543 changes for master"
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:money-claims, prd:cmc, destroy, rel:cmc-claim-store-pr-2799

#2800 CIV-10543 master making dbs on other enviornments
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:money-claims, prd:cmc, add-or-update, rel:cmc-claim-store-pr-2800

#2802 CIV-10543 fixing product value
  infrastructure/main.tf
Labels: ns:money-claims, prd:cmc, no-changes, rel:cmc-claim-store-pr-2802
