Repository hmcts/cmc-claim-store, pull requests merged in 2023-09, with the labels that each got.

#2765 CIV-10327 add bulk print service changes
  config/owasp/suppressions.xml
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandler.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/documents/PrintService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/breathingspace/BreathingSpaceLetterService.java
  src/main/java/uk/gov/hmcts/cmc/claimstore/utils/CaseDataExtractorUtils.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintHandlerTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/BulkPrintServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/documents/DummyBulkPrintServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/events/claim/PinOrchestrationServiceTest.java
  src/test/java/uk/gov/hmcts/cmc/claimstore/services/ccd/callbacks/caseworker/breathingspace/BreathingSpaceLetterServiceTest.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2765

#2766 ignore transitive dependencies
  build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2766

#2767 Fix/ignore transitive dependency
  build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2767

#2771 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2771

#2772 fix master
  Jenkinsfile_CNP
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2772

#2763 CIV-9920 increase max attempts and delay
  Jenkinsfile_CNP
  src/main/java/uk/gov/hmcts/cmc/claimstore/services/document/SecuredDocumentManagementService.java
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2763
