Repository hmcts/cmc-claim-store, pull requests merged in 2024-04, with the labels that each got.

#2843 DTSCCI-029: Add isle of wight court in court list in pilot court
  config/owasp/suppressions.xml
  src/main/resources/data/pilot-courts.csv
  src/test/resources/pilot-court/pilot-courts-LA.csv
  src/test/resources/pilot-court/pilot-courts.csv
  src/test/resources/pilot-court/response/ALL_PILOT_COURT_IDS.json
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2843

#2844 DTSCCI-060 Reduce CVEs
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2844

#2846 DTSCCI-060 Reduce CVEs
  build.gradle
  ccd-adapter/build.gradle
  ccd-sample-data/build.gradle
  config/owasp/suppressions.xml
  domain-model/build.gradle
  job-scheduler/build.gradle
  launch-darkly-client/build.gradle
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2846

#2633 DTSSE-1790 Update README
  README.md
Labels: ns:money-claims, prd:cmc, rel:cmc-claim-store-pr-2633
